# Continuous Integration
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: judevops.azurecr.io
          username: ${{ secrets.Ahmednur_USERNAME }}
          password: ${{ secrets.Ahmednur_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t judevops.azurecr.io/ahmednur-calculator:latest -f BE/dockerfile BE/

      - name: Push Docker image
        run: |
          docker push judevops.azurecr.io/ahmednur-calculator:latest
